// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: txmsg.proto

/*
Package txmsg is a generated protocol buffer package.

It is generated from these files:
	txmsg.proto

It has these top-level messages:
	LDCreateAccountTx
	LDAppState
	LDStateQueryParams
	LDStateQueryResult
	LDRollQueryParams
	LDRollQueryResult
	LDChipQueryParams
	LDChipQueryResult
*/
package txmsg

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type LDCreateAccountTx struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *LDCreateAccountTx) Reset()                    { *m = LDCreateAccountTx{} }
func (m *LDCreateAccountTx) String() string            { return proto.CompactTextString(m) }
func (*LDCreateAccountTx) ProtoMessage()               {}
func (*LDCreateAccountTx) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{0} }

func (m *LDCreateAccountTx) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type LDAppState struct {
	State []byte `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *LDAppState) Reset()                    { *m = LDAppState{} }
func (m *LDAppState) String() string            { return proto.CompactTextString(m) }
func (*LDAppState) ProtoMessage()               {}
func (*LDAppState) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{1} }

func (m *LDAppState) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

type LDStateQueryParams struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *LDStateQueryParams) Reset()                    { *m = LDStateQueryParams{} }
func (m *LDStateQueryParams) String() string            { return proto.CompactTextString(m) }
func (*LDStateQueryParams) ProtoMessage()               {}
func (*LDStateQueryParams) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{2} }

func (m *LDStateQueryParams) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type LDStateQueryResult struct {
	State []byte `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
}

func (m *LDStateQueryResult) Reset()                    { *m = LDStateQueryResult{} }
func (m *LDStateQueryResult) String() string            { return proto.CompactTextString(m) }
func (*LDStateQueryResult) ProtoMessage()               {}
func (*LDStateQueryResult) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{3} }

func (m *LDStateQueryResult) GetState() []byte {
	if m != nil {
		return m.State
	}
	return nil
}

type LDRollQueryParams struct {
	Owner  string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	BetBig bool   `protobuf:"varint,2,opt,name=betBig,proto3" json:"betBig,omitempty"`
	Amount int32  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *LDRollQueryParams) Reset()                    { *m = LDRollQueryParams{} }
func (m *LDRollQueryParams) String() string            { return proto.CompactTextString(m) }
func (*LDRollQueryParams) ProtoMessage()               {}
func (*LDRollQueryParams) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{4} }

func (m *LDRollQueryParams) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *LDRollQueryParams) GetBetBig() bool {
	if m != nil {
		return m.BetBig
	}
	return false
}

func (m *LDRollQueryParams) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type LDRollQueryResult struct {
	Point  int32 `protobuf:"varint,1,opt,name=point,proto3" json:"point,omitempty"`
	Win    bool  `protobuf:"varint,2,opt,name=win,proto3" json:"win,omitempty"`
	Amount int32 `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *LDRollQueryResult) Reset()                    { *m = LDRollQueryResult{} }
func (m *LDRollQueryResult) String() string            { return proto.CompactTextString(m) }
func (*LDRollQueryResult) ProtoMessage()               {}
func (*LDRollQueryResult) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{5} }

func (m *LDRollQueryResult) GetPoint() int32 {
	if m != nil {
		return m.Point
	}
	return 0
}

func (m *LDRollQueryResult) GetWin() bool {
	if m != nil {
		return m.Win
	}
	return false
}

func (m *LDRollQueryResult) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type LDChipQueryParams struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *LDChipQueryParams) Reset()                    { *m = LDChipQueryParams{} }
func (m *LDChipQueryParams) String() string            { return proto.CompactTextString(m) }
func (*LDChipQueryParams) ProtoMessage()               {}
func (*LDChipQueryParams) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{6} }

func (m *LDChipQueryParams) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type LDChipQueryResult struct {
	Amount int32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *LDChipQueryResult) Reset()                    { *m = LDChipQueryResult{} }
func (m *LDChipQueryResult) String() string            { return proto.CompactTextString(m) }
func (*LDChipQueryResult) ProtoMessage()               {}
func (*LDChipQueryResult) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{7} }

func (m *LDChipQueryResult) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*LDCreateAccountTx)(nil), "LDCreateAccountTx")
	proto.RegisterType((*LDAppState)(nil), "LDAppState")
	proto.RegisterType((*LDStateQueryParams)(nil), "LDStateQueryParams")
	proto.RegisterType((*LDStateQueryResult)(nil), "LDStateQueryResult")
	proto.RegisterType((*LDRollQueryParams)(nil), "LDRollQueryParams")
	proto.RegisterType((*LDRollQueryResult)(nil), "LDRollQueryResult")
	proto.RegisterType((*LDChipQueryParams)(nil), "LDChipQueryParams")
	proto.RegisterType((*LDChipQueryResult)(nil), "LDChipQueryResult")
}

func init() { proto.RegisterFile("txmsg.proto", fileDescriptorTxmsg) }

var fileDescriptorTxmsg = []byte{
	// 230 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x91, 0x4d, 0x4b, 0xc4, 0x30,
	0x10, 0x86, 0x89, 0x4b, 0x17, 0x1d, 0x3d, 0x68, 0x10, 0xe9, 0xb1, 0xe4, 0x54, 0x15, 0xbc, 0xf8,
	0x0b, 0x56, 0x7b, 0xec, 0x41, 0xb3, 0x5e, 0x3c, 0x66, 0x97, 0xb0, 0x06, 0xda, 0x24, 0x24, 0x53,
	0x76, 0xfd, 0xf7, 0x92, 0x0f, 0xa8, 0x5d, 0x28, 0xbd, 0xcd, 0x1b, 0x1e, 0x9e, 0x4c, 0xde, 0xc0,
	0x35, 0x9e, 0x7a, 0x7f, 0x78, 0xb1, 0xce, 0xa0, 0x61, 0x8f, 0x70, 0xd7, 0x36, 0xef, 0x4e, 0x0a,
	0x94, 0x9b, 0xfd, 0xde, 0x0c, 0x1a, 0xbf, 0x4e, 0xf4, 0x1e, 0x0a, 0x73, 0xd4, 0xd2, 0x95, 0xa4,
	0x22, 0xf5, 0x15, 0x4f, 0x81, 0x31, 0x80, 0xb6, 0xd9, 0x58, 0xbb, 0x45, 0x81, 0x32, 0x30, 0x3e,
	0x0c, 0x91, 0xb9, 0xe1, 0x29, 0xb0, 0x27, 0xa0, 0x6d, 0x13, 0x81, 0xcf, 0x41, 0xba, 0xdf, 0x0f,
	0xe1, 0x44, 0xef, 0x67, 0x7c, 0x67, 0x2c, 0x97, 0x7e, 0xe8, 0x70, 0xc6, 0xfb, 0x1d, 0xd6, 0xe4,
	0xa6, 0xeb, 0x16, 0xb5, 0xf4, 0x01, 0xd6, 0x3b, 0x89, 0x6f, 0xea, 0x50, 0x5e, 0x54, 0xa4, 0xbe,
	0xe4, 0x39, 0x85, 0x73, 0xd1, 0x87, 0x07, 0x96, 0xab, 0x8a, 0xd4, 0x05, 0xcf, 0x89, 0x6d, 0x27,
	0xea, 0x71, 0x0b, 0x6b, 0x94, 0xc6, 0xa8, 0x2e, 0x78, 0x0a, 0xf4, 0x16, 0x56, 0x47, 0xa5, 0xb3,
	0x37, 0x8c, 0xb3, 0xd2, 0x54, 0xeb, 0x8f, 0xb2, 0xcb, 0x35, 0x3c, 0x4f, 0xd0, 0x7c, 0xff, 0xe8,
	0x25, 0xff, 0xbd, 0xbb, 0x75, 0xfc, 0xb5, 0xd7, 0xbf, 0x00, 0x00, 0x00, 0xff, 0xff, 0xc6, 0x4f,
	0x47, 0x62, 0xc4, 0x01, 0x00, 0x00,
}
