// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: txmsg.proto

/*
Package txmsg is a generated protocol buffer package.

It is generated from these files:
	txmsg.proto

It has these top-level messages:
	LoomDiceCreateAccountTx
	LoomDiceRoll
	LoomDiceRollResult
	LoomDiceAmountQueryParams
	LoomDiceAmountQueryResult
*/
package txmsg

import proto "github.com/gogo/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion2 // please upgrade the proto package

type LoomDiceCreateAccountTx struct {
	Version int32  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	Owner   string `protobuf:"bytes,2,opt,name=owner,proto3" json:"owner,omitempty"`
	Data    []byte `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (m *LoomDiceCreateAccountTx) Reset()                    { *m = LoomDiceCreateAccountTx{} }
func (m *LoomDiceCreateAccountTx) String() string            { return proto.CompactTextString(m) }
func (*LoomDiceCreateAccountTx) ProtoMessage()               {}
func (*LoomDiceCreateAccountTx) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{0} }

func (m *LoomDiceCreateAccountTx) GetVersion() int32 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *LoomDiceCreateAccountTx) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

func (m *LoomDiceCreateAccountTx) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoomDiceRoll struct {
	Owner  []byte `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
	Amount int32  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *LoomDiceRoll) Reset()                    { *m = LoomDiceRoll{} }
func (m *LoomDiceRoll) String() string            { return proto.CompactTextString(m) }
func (*LoomDiceRoll) ProtoMessage()               {}
func (*LoomDiceRoll) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{1} }

func (m *LoomDiceRoll) GetOwner() []byte {
	if m != nil {
		return m.Owner
	}
	return nil
}

func (m *LoomDiceRoll) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type LoomDiceRollResult struct {
	Result int32 `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
}

func (m *LoomDiceRollResult) Reset()                    { *m = LoomDiceRollResult{} }
func (m *LoomDiceRollResult) String() string            { return proto.CompactTextString(m) }
func (*LoomDiceRollResult) ProtoMessage()               {}
func (*LoomDiceRollResult) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{2} }

func (m *LoomDiceRollResult) GetResult() int32 {
	if m != nil {
		return m.Result
	}
	return 0
}

type LoomDiceAmountQueryParams struct {
	Owner string `protobuf:"bytes,1,opt,name=owner,proto3" json:"owner,omitempty"`
}

func (m *LoomDiceAmountQueryParams) Reset()                    { *m = LoomDiceAmountQueryParams{} }
func (m *LoomDiceAmountQueryParams) String() string            { return proto.CompactTextString(m) }
func (*LoomDiceAmountQueryParams) ProtoMessage()               {}
func (*LoomDiceAmountQueryParams) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{3} }

func (m *LoomDiceAmountQueryParams) GetOwner() string {
	if m != nil {
		return m.Owner
	}
	return ""
}

type LoomDiceAmountQueryResult struct {
	Amount int32 `protobuf:"varint,1,opt,name=amount,proto3" json:"amount,omitempty"`
}

func (m *LoomDiceAmountQueryResult) Reset()                    { *m = LoomDiceAmountQueryResult{} }
func (m *LoomDiceAmountQueryResult) String() string            { return proto.CompactTextString(m) }
func (*LoomDiceAmountQueryResult) ProtoMessage()               {}
func (*LoomDiceAmountQueryResult) Descriptor() ([]byte, []int) { return fileDescriptorTxmsg, []int{4} }

func (m *LoomDiceAmountQueryResult) GetAmount() int32 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func init() {
	proto.RegisterType((*LoomDiceCreateAccountTx)(nil), "LoomDiceCreateAccountTx")
	proto.RegisterType((*LoomDiceRoll)(nil), "LoomDiceRoll")
	proto.RegisterType((*LoomDiceRollResult)(nil), "LoomDiceRollResult")
	proto.RegisterType((*LoomDiceAmountQueryParams)(nil), "LoomDiceAmountQueryParams")
	proto.RegisterType((*LoomDiceAmountQueryResult)(nil), "LoomDiceAmountQueryResult")
}

func init() { proto.RegisterFile("txmsg.proto", fileDescriptorTxmsg) }

var fileDescriptorTxmsg = []byte{
	// 211 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2e, 0xa9, 0xc8, 0x2d,
	0x4e, 0xd7, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x57, 0x8a, 0xe5, 0x12, 0xf7, 0xc9, 0xcf, 0xcf, 0x75,
	0xc9, 0x4c, 0x4e, 0x75, 0x2e, 0x4a, 0x4d, 0x2c, 0x49, 0x75, 0x4c, 0x4e, 0xce, 0x2f, 0xcd, 0x2b,
	0x09, 0xa9, 0x10, 0x92, 0xe0, 0x62, 0x2f, 0x4b, 0x2d, 0x2a, 0xce, 0xcc, 0xcf, 0x93, 0x60, 0x54,
	0x60, 0xd4, 0x60, 0x0d, 0x82, 0x71, 0x85, 0x44, 0xb8, 0x58, 0xf3, 0xcb, 0xf3, 0x52, 0x8b, 0x24,
	0x98, 0x14, 0x18, 0x35, 0x38, 0x83, 0x20, 0x1c, 0x21, 0x21, 0x2e, 0x96, 0x94, 0xc4, 0x92, 0x44,
	0x09, 0x66, 0x05, 0x46, 0x0d, 0x9e, 0x20, 0x30, 0x5b, 0xc9, 0x86, 0x8b, 0x07, 0x66, 0x7c, 0x50,
	0x7e, 0x4e, 0x0e, 0x42, 0x27, 0x23, 0x58, 0x11, 0x54, 0xa7, 0x18, 0x17, 0x5b, 0x62, 0x2e, 0xc8,
	0x56, 0xb0, 0x81, 0xac, 0x41, 0x50, 0x9e, 0x92, 0x0e, 0x97, 0x10, 0xb2, 0xee, 0xa0, 0xd4, 0xe2,
	0xd2, 0x9c, 0x12, 0x90, 0xea, 0x22, 0x30, 0x0b, 0xea, 0x2c, 0x28, 0x4f, 0xc9, 0x90, 0x4b, 0x12,
	0xa6, 0xda, 0x11, 0xac, 0x3f, 0xb0, 0x34, 0xb5, 0xa8, 0x32, 0x20, 0xb1, 0x28, 0x31, 0xb7, 0x18,
	0xd5, 0x62, 0x98, 0x93, 0x95, 0x8c, 0xb1, 0x6a, 0x41, 0xd8, 0x03, 0x75, 0x15, 0x23, 0xb2, 0xab,
	0x92, 0xd8, 0xc0, 0x21, 0x67, 0x0c, 0x08, 0x00, 0x00, 0xff, 0xff, 0xee, 0xcd, 0xd6, 0x76, 0x48,
	0x01, 0x00, 0x00,
}
